FROM node:20-slim AS base
WORKDIR /usr/src/app
COPY package*.json ./

# ---- Dependencies ----
FROM base AS dependencies
RUN npm install
COPY . .
# Ensure the CA certificate for the database is copied if needed by kysely
COPY ca.crt ./ca.crt

# ---- Build ----
FROM dependencies AS build
RUN npx --yes kysely-codegen --url "postgresql://postgres:m2plpy8dF1ceckCW@insipidly-accredited-spaniel.data-1.use1.tembo.io:5432/postgres?sslmode=verify-full&sslrootcert=ca.crt"
RUN npm run build

# ---- Release ----
FROM base AS release
# Set environment to production
ENV NODE_ENV=production
# Install *only* production dependencies
RUN npm install --omit=dev

# Copy necessary artifacts from the previous stages
COPY --from=build /usr/src/app/dist ./dist
COPY --from=build /usr/src/app/node_modules ./node_modules
COPY --from=build /usr/src/app/ca.crt ./ca.crt

EXPOSE 8000


# Define the command to run the application
CMD ["sh", "-c", "node dist/server.js | npx pino-pretty"]